var load=require('../../../../lib/load.js');
var dateUtils=require('../../../../utils/dateUtil');
import config from '../../../../config.js';
import * as echarts from '../../../ec-canvas/echarts';
import { getNxUnitPriceAnalysis } from '../../../../lib/apiDepOrder.js';
var globalData=getApp().globalData;
var ICON_ROOT='/subPackage-charts/images/purchase/icon_pack/';
function num(v){var n=Number(v);return isNaN(n)?0:n;}
function imageUrl(v){return!v?'':(/^https?:\/\//.test(v)?v:config.server+v);}
function parse(v){var p=v.split('-');return new Date(Number(p[0]),Number(p[1])-1,Number(p[2]));}
function iso(d){var m=d.getMonth()+1,day=d.getDate();return d.getFullYear()+'-'+(m<10?'0':'')+m+'-'+(day<10?'0':'')+day;}
Page({
 data:{navBarHeight:0,iconRoot:ICON_ROOT,bannerUrl:'/subPackage-charts/images/purchase/unit-price-analysis-banner.jpg',metric:'price',ecTrend:{lazyLoad:true},loading:true,hasData:false,sourceIndex:0,sourceNames:['全部来源','自采','供货商'],sourceValues:['ALL','SELF','SUPPLIER'],departmentIndex:0,departmentList:[{nxDepartmentId:0,nxDepartmentName:'全部部门'}],departmentNames:['全部部门'],goodsIndex:0,goodsNames:['全部商品'],goodsOptions:[{id:0,name:'全部商品'}],selectedGoodsId:0,summary:{},goods:[],reminders:[]},
 onLoad:function(){var dis=wx.getStorageSync('disInfo')||{},deps=[{nxDepartmentId:0,nxDepartmentName:'全部部门'}];this.setData({navBarHeight:globalData.navBarHeight*globalData.rpxR,disId:dis.nxDistributerId,departmentList:deps,departmentNames:deps.map(function(x){return x.nxDepartmentName;})});this._syncDate();this._load();},
 onShow:function(){if(this.data.update){this.setData({update:false});wx.setStorageSync('purchaseAnalysisDate',{name:'custom',dateType:'month',startDate:this.data.startDate,stopDate:this.data.stopDate,hanzi:this.data.hanzi||'自定义'});this._load();}},onPullDownRefresh:function(){this._load();},
 _syncDate:function(){var saved=wx.getStorageSync('purchaseAnalysisDate') || wx.getStorageSync('myDate'),start=dateUtils.getFirstDateInMonth(),stop=dateUtils.getArriveDate(0),hanzi='本月';if(saved){var range=saved.name==='custom'?dateUtils.getDateRange(saved.name,saved.startDate,saved.stopDate):dateUtils.getDateRange(saved.name);start=range.startDate;stop=range.stopDate;hanzi=saved.hanzi||range.name;}this.setData({startDate:start,stopDate:stop,hanzi:hanzi});},
 toDatePage:function(){wx.navigateTo({url:'/subPackage-charts/pages/sel/searchDate/searchDate?startDate='+this.data.startDate+'&stopDate='+this.data.stopDate+'&dateType=month'});},
 changeSource:function(e){this.setData({sourceIndex:Number(e.detail.value),goodsIndex:0,selectedGoodsId:0,goodsOptions:[{id:0,name:'全部商品'}],goodsNames:['全部商品']});this._load();},
 changeDepartment:function(e){this.setData({departmentIndex:Number(e.detail.value),goodsIndex:0,selectedGoodsId:0,goodsOptions:[{id:0,name:'全部商品'}],goodsNames:['全部商品']});this._load();},
 changeGoods:function(e){var index=Number(e.detail.value),option=this.data.goodsOptions[index]||this.data.goodsOptions[0];this.setData({goodsIndex:index,selectedGoodsId:option.id});this._load();},
 switchMetric:function(e){this.setData({metric:e.currentTarget.dataset.metric},this._scheduleChart.bind(this));},
 _load:function(){var that=this,dep=this.data.departmentList[this.data.departmentIndex]||{};if(!this.data.disId){load.showToast('缺少分销商信息');return;}this.setData({loading:true});load.showLoading('获取数据中');getNxUnitPriceAnalysis({disId:this.data.disId,startDate:this.data.startDate,stopDate:this.data.stopDate,sourceType:this.data.sourceValues[this.data.sourceIndex],departmentId:dep.nxDepartmentId||'',disGoodsId:this.data.selectedGoodsId||''}).then(function(res){load.hideLoading();wx.stopPullDownRefresh();if(!res.result||res.result.code!==0){that.setData({loading:false,hasData:false});load.showToast((res.result&&res.result.msg)||'获取失败');return;}that._apply(res.result.data||{});}).catch(function(){load.hideLoading();wx.stopPullDownRefresh();that.setData({loading:false,hasData:false});load.showToast('网络请求失败');});},
 _fillDays:function(rows){var map={};(rows||[]).forEach(function(x){map[x.day]=x;});var out=[],d=parse(this.data.startDate),end=parse(this.data.stopDate);while(d<=end){var key=iso(d);out.push(map[key]||{day:key,averageUnitPrice:null,fluctuationRate:null});d.setDate(d.getDate()+1);}return out;},
 _apply:function(data){var s=data.summary||{},rows=(data.goods||[]).map(function(x){var rate=num(x.priceChangePercent),status=rate>0?'价格上涨':rate<0?'价格下降':'价格稳定',dir=rate>0?'up':rate<0?'down':'stable';return Object.assign({},x,{image:imageUrl(x.goodsImage),initial:String(x.goodsName||'商').slice(0,1),rateAbs:Math.abs(rate).toFixed(1),directionClass:dir,statusText:status,currentPrice:num(x.currentUnitPrice).toFixed(1),previousPrice:num(x.previousUnitPrice).toFixed(1)});});var update={loading:false,hasData:rows.length>0,daily:this._fillDays(data.priceTrend||[]),goods:rows,reminders:data.reminders||[],summary:{changed:num(s.fluctuatingGoodsCount),total:num(s.totalGoodsCount),changedRate:num(s.totalGoodsCount)?(num(s.fluctuatingGoodsCount)*100/num(s.totalGoodsCount)).toFixed(1):'0.0',average:num(s.averageFluctuationRate).toFixed(1),rising:num(s.risingGoodsCount),falling:num(s.fallingGoodsCount)}};if(!this.data.selectedGoodsId){var options=[{id:0,name:'全部商品'}].concat(rows.map(function(x){return{id:x.disGoodsId,name:x.goodsName};}));update.goodsOptions=options;update.goodsNames=options.map(function(x){return x.name;});}this.setData(update,this._scheduleChart.bind(this));},
 _scheduleChart:function(){var that=this;wx.nextTick(function(){setTimeout(function(){that._drawChart();},80);});},
 _drawChart:function(){if(!this.data.hasData)return;var c=this.selectComponent('#priceTrendChart'),that=this;if(!c){this._chartAttempts=(this._chartAttempts||0)+1;if(this._chartAttempts<6)setTimeout(this._drawChart.bind(this),100);return;}this._chartAttempts=0;var rows=this.data.daily||[],metric=this.data.metric;c.init(function(canvas,width,height,dpr){if(that.priceChart)that.priceChart.dispose();var chart=echarts.init(canvas,null,{width:width,height:height,devicePixelRatio:dpr});that.priceChart=chart;chart.setOption({grid:{left:10,right:10,top:26,bottom:8,containLabel:true},xAxis:{type:'category',boundaryGap:false,data:rows.map(function(x){var p=x.day.split('-');return Number(p[1])+'/'+Number(p[2]);}),axisTick:{show:false},axisLine:{lineStyle:{color:'#dce9e5'}},axisLabel:{fontSize:11,color:'#718198',interval:rows.length>16?2:0}},yAxis:{type:'value',splitNumber:3,axisLine:{show:false},axisTick:{show:false},axisLabel:{fontSize:11,color:'#718198'},splitLine:{lineStyle:{color:'#edf4f2'}}},series:[{type:'line',smooth:true,connectNulls:true,symbol:'circle',symbolSize:7,data:rows.map(function(x){var v=metric==='price'?x.averageUnitPrice:x.fluctuationRate;return v===null?null:num(v);}),lineStyle:{color:'#10b979',width:3},itemStyle:{color:'#fff',borderColor:'#10b979',borderWidth:2},areaStyle:{color:'rgba(41,200,139,.16)'}}]});return chart;});},
 toGoods:function(e){var item=e.currentTarget.dataset.item;wx.setStorageSync('disGoods',item);wx.navigateTo({url:'/subPackage-charts/pages/mangement/purchaseCategoryDetail/purchaseCategoryDetail?focusGoodsId='+item.disGoodsId});},toBack:function(){wx.navigateBack({delta:1});}
});
