import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const js = readFileSync('components/inputPurStock/inputPurStock.js', 'utf8')
const wxml = readFileSync('components/inputPurStock/inputPurStock.wxml', 'utf8')
const wxss = readFileSync('components/inputPurStock/inputPurStock.wxss', 'utf8')
const shelfWxml = readFileSync('subPackage/pages/shelf/index/index.wxml', 'utf8')

assert.doesNotMatch(wxml, /hold-keyboard/)
assert.equal((wxml.match(/confirm-type="done"/g) || []).length, 4)
assert.equal((wxml.match(/bindconfirm="hideKeyboard"/g) || []).length, 4)
assert.equal((wxml.match(/bindtap="hideKeyboard"/g) || []).length, 3)
assert.match(js, /_hideKeyboard\(\)[\s\S]*wx\.hideKeyboard/)
assert.match(js, /_checkPrice\(e\)\s*\{\s*this\._hideKeyboard\(\)/)
assert.match(js, /_checkQuantity\(e\)\s*\{\s*this\._hideKeyboard\(\)/)
assert.match(js, /onProduceDateChange\(e\)\s*\{\s*this\._hideKeyboard\(\)/)
assert.match(js, /onShelfLifeUnitChange\(e\)\s*\{\s*this\._hideKeyboard\(\)/)
assert.match(js, /onExpiryDateChange\(e\)\s*\{\s*this\._hideKeyboard\(\)/)
assert.match(js, /confirm\(e\)\s*\{\s*this\._hideKeyboard\(\)/)
assert.match(js, /showWaitOption:\s*\{[\s\S]*?value:\s*false/)
assert.match(wxml, /!receiptOnly && showWaitOption/)
assert.match(shelfWxml, /show-wait-option="\{\{false\}\}"/)
assert.match(wxss, /min-height:\s*104rpx/)
assert.match(wxss, /height:\s*68rpx/)
assert.match(wxss, /padding-top:\s*12rpx/)
assert.match(wxss, /padding-bottom:\s*12rpx/)
assert.match(js, /_receiptConversionFactor\(item\)/)
assert.match(js, /purchasePrice \/ factor\)\.toFixed\(1\)/)
assert.ok(wxml.includes('value="{{receiptOnly ? receiptExpectedBasePrice'))
assert.ok(wxml.includes('<text wx:if="{{receiptOnly}}">元/{{item.nxDistributerGoodsEntity.nxDgGoodsStandardname}}</text>'))
assert.doesNotMatch(wxml, /value="\{\{receiptOnly \? receiptExpectedBasePrice[^\n]+disabled=/)

console.log('inputPurStock keyboard, receipt pricing and compact layout: PASS (23 checks)')
