import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8')

const appJson = JSON.parse(read('app.json'))
const charts = appJson.subPackages.find(item => item.root === 'subPackage-charts/')
assert.ok(charts.pages.includes('pages/smartReplenishment/index/index'))
assert.ok(charts.pages.includes('pages/smartReplenishment/customerPicker/customerPicker'))
assert.ok(charts.pages.includes('pages/sel/date/date'))
assert.ok(!charts.pages.includes('pages/smartReplenishment/datePicker/datePicker'))

const homeJs = read('subPackage/pages/management/homePage/homePage.js')
const homeWxml = read('subPackage/pages/management/homePage/homePage.wxml')
const pageJs = read('subPackage-charts/pages/smartReplenishment/index/index.js')
const pageWxml = read('subPackage-charts/pages/smartReplenishment/index/index.wxml')
const pickerJs = read('subPackage-charts/pages/smartReplenishment/customerPicker/customerPicker.js')
const pickerWxml = read('subPackage-charts/pages/smartReplenishment/customerPicker/customerPicker.wxml')
const pageWxss = read('subPackage-charts/pages/smartReplenishment/index/index.wxss')
const api = read('lib/apiDistributer.js')

assert.match(homeWxml, /bindtap="toSmartReplenishment"/)
assert.match(homeWxml, /wx:if="\{\{canViewSmartReplenishment\}\}"/)
assert.match(homeJs, /Number\(.*nxDiuAdmin\) === 0/)
assert.match(homeJs, /pages\/smartReplenishment\/index\/index/)

assert.match(pageWxml, /bindtap="toCustomerPicker"/)
assert.match(pageWxml, /class="smart-control-panel"/)
assert.match(pageWxml, /class="current-date-copy"/)
assert.match(pageWxml, /tool\.transferDateString\(startDate\)/)
assert.doesNotMatch(pageWxml, /calender\.png/)
assert.doesNotMatch(pageJs, /pages\/sel\/date\/date/)
assert.doesNotMatch(pageJs, /pages\/smartReplenishment\/datePicker\/datePicker/)
assert.match(pageWxml, /data-mode="TODAY"/)
assert.match(pageWxml, /data-mode="TOMORROW"/)
assert.match(pageWxml, /data-mode="NEXT_7"/)
assert.match(pageWxml, /data-mode="CUSTOM"/)
assert.match(pageWxml, /class="custom-date-sheet"/)
assert.match(pageWxml, /start="\{\{forecastToday\}\}"/)
assert.match(pageWxml, /end="\{\{maxForecastDate\}\}"/)
assert.match(pageJs, /selectDateMode/)
assert.match(pageJs, /confirmCustomDate/)
assert.match(pageJs, /validateForecastRange/)
assert.match(pageWxss, /\.custom-date-mask\s*\{[\s\S]*align-items:\s*flex-end;/)
assert.match(pageWxml, /class="customer-filter-button"/)
assert.match(pageWxml, /filter-3-fill\.png/)
assert.match(pageWxml, /filter\.png/)
assert.match(pageWxml, /class="selected-customer-chip"/)
assert.match(pageWxml, /selectedDepartmentName/)
assert.match(pageWxml, /\/images\/del\.png/)
assert.match(pageJs, /clearCustomerFilter/)
assert.match(pageJs, /join\('，'\)/)
assert.match(pageJs, /departmentIds/)
assert.match(pageJs, /pages\/smartReplenishment\/customerPicker/)
assert.match(pickerWxml, /搜索客户名称/)
assert.match(pickerWxml, /全部客户/)
assert.match(pickerJs, /getCurrentPages\(\)/)
assert.match(pickerJs, /applyCustomerSelection/)
assert.match(pickerJs, /selectedIds/)
assert.match(pickerJs, /confirmSelection/)
assert.match(pickerWxml, /multi-check/)
assert.match(pickerWxml, /bindtap="confirmSelection"/)

assert.match(pageWxml, /class="compact-workspace"/)
assert.match(pageWxml, /自采商品/)
assert.match(pageWxml, /出库商品/)
assert.match(pageWxml, /bindtap="selectGoodsType"/)
assert.match(pageWxml, /item\.goodsTypeText/)
assert.ok(pageWxml.indexOf('item.goodsTypeText') < pageWxml.indexOf('item.levelLetter'))
assert.match(pageWxml, /prediction-summary-strip/)
assert.match(pageWxml, /predictionSummary\.levelA/)
assert.match(pageWxml, /predictionSummary\.levelB/)
assert.match(pageWxml, /item\.trustText/)
assert.match(pageWxml, /item\.levelLetter/)
assert.match(pageWxml, /item\.goodsName/)
assert.match(pageWxml, /预计 \{\{item\.predictedQuantityText\}\}\{\{item\.predictedUnit\}\}/)
assert.match(pageWxml, /item\.departmentLines/)
assert.match(pageWxml, /line\.forecastItems/)
assert.match(pageWxml, /class="forecast-chip"/)
assert.match(pageWxml, /forecast\.dateText/)
assert.match(pageWxml, /forecast\.quantityText/)
assert.doesNotMatch(pageWxml, /class="forecast-chip-scroll"/)
assert.match(pageWxml, /class="current-purchase-button/)
assert.match(pageWxml, /bindtap="editProcurement"/)
assert.match(pageWxml, /添加采购/)
assert.match(pageWxml, /bindinput="onPurchaseQuantityInput"/)
assert.match(pageWxml, /value="\{\{purchaseQuantity\}\}"/)
assert.match(pageWxml, /bindinput="onPurchaseUnitInput"/)
assert.match(pageWxml, /value="\{\{purchaseUnit\}\}"/)
assert.match(pageWxml, /bindkeyboardheightchange="onPurchaseKeyboardHeightChange"/)
assert.match(pageWxml, /bindtap="deleteProcurement"/)
assert.match(pageWxss, /\.page-scroll\s*\{[\s\S]*position: fixed;[\s\S]*bottom: 0;/)
assert.match(pageWxss, /\.selected-customer-chip\s*\{[\s\S]*width: auto;[\s\S]*background: #168878;/)
assert.match(pageWxss, /\.forecast-chip\s*\{[\s\S]*background: #edf9f4;/)
assert.match(pageWxss, /\.forecast-chip > strong\s*\{[\s\S]*font-size: 30rpx;/)
assert.match(pageWxss, /\.forecast-chip-list\s*\{[\s\S]*flex-wrap: wrap;/)
assert.doesNotMatch(pageWxml, /item\.detailText \|\| item\.categoryName/)
assert.doesNotMatch(pageWxml, /summary-grid|A 直接备货|B 联系确认|库存数量|建议操作|预测依据/)
assert.match(pageWxml, /class="goods-photo"/)
assert.match(pageWxml, /src="\{\{item\.imageUrl\}\}"/)
assert.match(pageJs, /forecastSmartReplenishment/)
assert.match(pageJs, /getSmartReplenishmentContexts/)
assert.match(pageJs, /createSmartReplenishmentProcurement/)
assert.match(pageJs, /updateSmartReplenishmentProcurement/)
assert.match(pageJs, /deleteSmartReplenishmentProcurement/)
assert.match(pageJs, /algorithmVersion: BASELINE/)
assert.match(pageJs, /historyWindowDays: 30/)
assert.match(pageJs, /apiUrl\.server/)

const smartApiStart = api.indexOf('const ownerSmartReplenishmentRequest')
const smartApiEnd = api.indexOf('老板端当前配送商全部客户订货异常汇总')
const smartApi = api.slice(smartApiStart, smartApiEnd)
assert.match(smartApi, /purchase-prediction-lab\/' \+ path/)
assert.match(smartApi, /ownerSmartReplenishmentRequest\('forecasts', 'POST', data\)/)
assert.match(smartApi, /\/quantity/)
assert.match(smartApi, /\/delete/)
assert.match(smartApi, /'goods\/' \+ encodeURIComponent\(goodsId\)/)
assert.doesNotMatch(smartApi, /nxdistributergoods\/disGetGoods/)
assert.doesNotMatch(smartApi, /demand_source|demandSource|business_event_type|businessEventType|procurement_mode|procurementMode|apply_shelf_id|applyShelfId/)

console.log('smart replenishment page contract tests passed')
