const fs = require('fs')
const path = require('path')
const assert = require('assert')

const root = path.resolve(__dirname, '../..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')

const app = JSON.parse(read('app.json'))
const api = read('lib/apiDistributer.js')
const shelf = read('subPackage/pages/shelf/index/index.js')
const page = read('subPackage/pages/prepare/purchaseReceipt/purchaseReceipt.js')
const view = read('subPackage/pages/prepare/purchaseReceipt/purchaseReceipt.wxml')

assert.ok(app.subPackages.some(item => item.pages.includes('pages/prepare/purchaseReceipt/purchaseReceipt')))
assert.ok(api.includes("url: apiUrl.apiUrl + 'purchasereceipts/batches/'"))
assert.ok(api.includes('getApp().ownerRequest({'))
assert.ok(api.includes("header['X-Idempotency-Key']"))
assert.ok(shelf.includes('/subPackage/pages/prepare/purchaseReceipt/purchaseReceipt?batchId='))
assert.ok(page.includes('confirmPurchaseReceipt('))
assert.ok(page.includes('stockInPurchaseReceipt('))
assert.ok(page.includes('returnPurchaseReceiptToSupplier('))
assert.ok(view.includes('预计金额'))
assert.ok(view.includes('实际收货'))
assert.ok(view.includes('实际净采购'))
assert.ok(view.includes('待入库'))
assert.ok(view.includes('不需要入库'))
assert.ok(view.includes('从库存退还'))

console.log('PASS Boss phase 1B purchase receipt contract')
